SERVICENOW:
  url: "https://<servicenow_instance>.service-now.com/api/now/table/incident"
  username: "your_user"
  password: "your_pass"
  proxy:
    http: "http://proxy_host:proxy_port"
    https: "http://proxy_host:proxy_port"

PATHS:
  daily_log_path: "/opt/CONTROL-M/ctm"
  sysout_source_dir: "/opt/CONTROL-M/ctm/sysout"
  sysout_archive_dir: "./static/logs"
  processed_data_dir: "./data"

OTHER:
  lookback_days: 30
