SERVICENOW:
  url: "https://your_instance.service-now.com/api/now/table/incident"
  username: "your_username"
  password: "your_password"
  proxy:
    http: "http://your.proxy.com:8080"
    https: "http://your.proxy.com:8080"

PATHS:
  daily_log_path: "/opt/CONTROL-M/ctm"
  sysout_source_dir: "/opt/CONTROL-M/ctm/sysout"
  sysout_archive_dir: "./static/logs"
  processed_data_dir: "./data"
